# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/2i2c-pilot-documentation/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "16"
  jobs:
    pre_build:
      # Generate the feature table in about/distributions/index.md.
      - "cd scripts; python feature-table.py"

sphinx:
  configuration: conf.py
  builder: dirhtml

# Explicitly opt out of trying to build additional formats such as PDF and ePub
formats: []

python:
  install:
    - requirements: requirements.txt
