contact_links:
  - name: "\U0001FA90 Questions about 2i2c or 2i2c Hubs?"
    url: https://2i2c.org#contact
    about: If you've got questions about 2i2c or the 2i2c Hubs, or if you're interested in getting your own 2i2c Hub, reach out at this link.
