name: Add readthedocs preview link to pull requests

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  autolink-rtd-previews:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          # The project slug in RTD still has the old repo name
          project-slug: "2i2c-pilot-documentation"
